version: '3.3'
services:
  nodebackend:
    container_name: backend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3006:3006
    env_file: .env
    depends_on:
      - db
    environment:
      - NODE_ENV=development
  db:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
