version: '3.3'
services:
  nodebackend:
    container_name: backend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3006:3006
    env_file: .env
    depends_on:
      - db
    environment:
      - NODE_ENV=production
  db:
    image: postgres
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=recipes
    ports: 
      - '5432:5432'
    volumes:
    - ./data/db:/data/db
