version: '3.3'
services:
  nodebackend:
    container_name: backend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3006:3006
    env_file: .env
    environment:
      - NODE_ENV=development
